### ISSUE TITLE
Loonium causes server crash

### ISSUE THREAD

**Issue by Borbarad13** [VazkiiMods/Botania#3796]
# Version Information
Forge version: 36.1.32
Botania version:  1.16.5-419

# Further Information
Link to crash log:
Caused by: java.lang.NullPointerException
    at net.minecraft.entity.Entity.func_241841_a(Entity.java:1980) ~[?:?]
    at net.minecraft.entity.monster.CreeperEntity.func_241841_a(CreeperEntity.java:196) ~[?:?]
    at vazkii.botania.common.block.subtile.functional.SubTileLoonuim.tickFlower(SubTileLoonuim.java:99) ~[botania:1.16.5-419]
    at vazkii.botania.api.subtile.TileEntitySpecialFlower.func_73660_a(TileEntitySpecialFlower.java:120) ~[botania:1.16.5-419]
    at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]

Steps to reproduce:
1. Run the vault hunters modpack
2. Place a working loonium down
3. The flower works normally most of the time, but the server crashes occasionally with the above log (maybe two hours after running). 
4. Maybe takes like 2 hours of running.

What I expected to happen:
Other modpacks are changing the loot tables, but I would expect the loonium flower class to be fault tolerant, so that the worst thing that happens is that loot is skipped or something, but not take down the whole server.

What happened instead:
Crash

**Comment by williewillus** [comment]
It's not related to the loot tables, it's actually a crash trying to mark the creeper as charged. Maybe we can make it more robust.

https://github.com/VazkiiMods/Botania/blob/master/src/main/java/vazkii/botania/common/block/subtile/functional/SubTileLoonuim.java#L99
